name: flutterl10nmanager
description: A package to help manage multiple languages in a Flutter project.
# version: 1.0.0
# homepage: https://www.example.com
# author: Warren Amphlett <warren@remarkablelives.co.uk>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  csv: ^4.0.3
  intl: ^0.15.8

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
